### ISSUE TITLE
Release v2.0.0

### ISSUE THREAD

**Issue by a1ex4** [a1ex4/ownfoil#43]
Ownfoil v2 is a complete rewrite of the project, using a web framework that allows much more flexibility. Instead of generating a static shop file (custom .tfl index) and serving it with Nginx, the shop is now directly served with an HTTP API when Tinfoil connects. It is far from completed, but should address all the main issues with the current implementation. It's available in the `v2` branch.

The main advantages of the v2 are:

- Library is scanned each time the shop is accessed
- The shop is served with an HTTP API endpoint, no more writing to a file in the library, hence no permission issue
- Settings and user creation is all done through a Web UI
- The library can be viewed from the Web UI

### Roadmap to release
In no particular order, things left to do before releasing Ownfoil v2:

- [x] Shop generation and Tinfoil access working
- [x] App settings saved and read from a file in `/config/settings.yaml`
- [x] Auth: setup user based permissions (Shop Access, Backup Access, Admin Access)
- [x] Library: download titledb files on first run (git clone)
- [x] Dockerize it
- [x] Github actions
- [x] Auth: Private / public shop
- [x] Auth: add warning if no Admin user exists
- [x] Library scan: use console keys to decrypt and identify files
- [x] Upload and validate console keys through the UI
- [x] Auth: Private / public library view
- [x] Auth: finish login page
- [x] Auth: admin user has all rights, not just "admin"
- [x] Backend: fork updated NSC_builder and include as a submodule / publish on pypi
- [x] Library view: add dropdown with select filters (up to date, out of date, base, dlc)
- [x] Library view: add DLC update status
- [x] Library view: add missing DLC status
- [x] Server: try running behind reverse proxy with HTTPS
- [x] Library: implement titles.json generation from all files
- [x] Library view: build games list on the frontend
- [x] Library view: add pagination
- [x] Library view: add icon view
- [x] Library scan: support multiple library paths
- [x] Library scan: add file watcher on the library path to update the db each change (added/renamed/deleted)
- [x] Add logging everywhere
- [x] Library: regularly update titledb
- [x] Shop generation: encrypted shop toggle
- [x] Refactor and clean code structure
- [ ] Auth: ability to change user password/permissions
- [ ] UI: Add toast notification for every API call
- [ ] Library view: add tooltip for version information
- [ ] Server: add server port as an app setting
- [ ] Library: rename files according to template
- [ ] Library access: use random uid instead of db index
- [ ] Library view: add list view
- [ ] Include js/css in static files
- [ ] Write `Setup` page to guide users on how to access the shop on Tinfoil, DBI... (http adress, port, auth...)
- [ ] Use a Bootstrap theme, with dark/light detection like [flatly](https://bootswatch.com/flatly/)

### How to test
To report issues and/or discuss about v2, see the discussion: #52 
Use v2 tag, built every commit pushed to the v2 branch:
```
version: "3"

services:
  ownfoil:
    container_name: ownfoil
    image: a1ex4/ownfoil:v2
    environment:
      # For write permission in config directory
      - PUID=1000
      - PGID=1000
    volumes:
      - /your/game/directory:/games
      - ./config:/app/config
    ports:
      - "8465:8465"
```

**Comment by SamuelBanya** [comment]
Will this also be included in the Docker container release via 'docker compose'?

Asking since my setup uses Portainer with the related 'Docker compose' file.

**Comment by CortezSMz** [comment]
What are the planned developments regarding the save manager?

**Comment by SiscuPrats** [comment]
Wow, it looks great. I'm looking forward to try it. Do you have a test version for docker? I could be a tester if you want.

Cheer up with the project.

**Comment by SiscuPrats** [comment]
Could you generate a docker container to test the 2.0 version? Thank you very much for your time and project.

**Comment by a1ex4** [comment]
@SamuelBanya @SiscuPrats Docker image for testing v2 is available, see the issue description.

@CortezSMz The save manager implementation will come later, I need to implement separate permission for each user (Shop Access, Library Access, Backup Access, Admin), then a profile page for users who can manage backups, then auto discovery of Switch device and linking it to a user... This means lots of development in the backend and fronted.
